In [1]:
# 1. In matematica, intervalul este definit ca diferenta dintre cel mai mare si cel mai mic numar
# dintr-o lista. De exemplu:
A = (3, 5, 7, 23, 11, 42, 80)
# Intervalul lui A este 80 - 3 = 77

# Creati o functie care primeste o lista si intoarce ":)" daca intervalul listei este egal cu un alt element,
# sau ":(" in caz contrar. Daca argumentul nu este o lista se intoarce ":/". Lista nu contine duplicate. 
# De exemplu:
# 
# face_interval([1, 2, 5, 8, 3, 9]) ➞ ":)"
#
# face_interval([5, 2, 8, 3, 11]) ➞ ":("
#
# face_interval("bruh") ➞ ":/"

In [1]:
import numpy as np

In [16]:
A = [3, 5, 7, 23, 11, 42, 80]


def face_interval(l):
    if type(l) is not list:
        return ':/'
    
    return ':)' if (max(l) - min(l)) in l else ':('

assert face_interval([1, 2, 5, 8, 3, 9]) == ":)"

assert face_interval([5, 2, 8, 3, 11]) == ":("

assert face_interval("bruh") == ":/"

In [2]:
# 2. Operatorul de shiftare la dreapta e similar cu aplicarea floor la rezultatul impartirii 
# prin puterile lui 2. De exemplu:
#
# 80 >> 3 = floor(80/2^3) = floor(80/8) = 10
# -24 >> 2 = floor(-24/2^2) = floor(-24/4) = -6
# -5 >> 1 = floor(-5/2^1) = floor(-5/2) = -3

# Scrieti o functie care realizeaza acest lucru, fara a folosi operatorul de shift >>.
# Exemple:

# shift_to_right(80, 3) ➞ 10
#
# shift_to_right(-24, 2) ➞ -6
#
# shift_to_right(-5, 1) ➞ -3
#
# shift_to_right(4666, 6) ➞ 72
#
# shift_to_right(3777, 6) ➞ 59
#
# shift_to_right(-512, 10) ➞ -1

# Obs:
# * al doilea parametru nu poate lua valori negative;
# * sub nici o forma nu va veti folosi de operatorul de shift;
# * rezolvati problema atat recursiv cat si iterativ.

In [3]:
# 3. Imaginati-va un cerc si doua patrate: unul mic, inscris in cerc, si unul mare, circumscris cercului.
# Patratele sunt presupuse a avea laturile paralele. Creati o functie care primeste un parametru intreg (raza
# cercului) si intoarce diferenta dintre ariile celor doua patrate. De exemplu:

# square_areas_difference(5) ➞ 5
# square_areas_difference(6) ➞ 72
# square_areas_difference(7) ➞ 98

In [4]:
# 4. Lucrati pentru o fabrica si e necesar sa calculati profitul total realizat din vanzarea unui produs.
# Aveti un dictionar care contine costul de productie, (cost_price), pretul de vanzare (sell_price)
# precum si numarul de bucati (inventory). Calculati profitul total realizat, rotunjit in sus la valoarea
# intreaga. De exemplu:

# profit({
#  "cost_price": 32.67,
#  "sell_price": 45.00,
#  "inventory": 1200
# }) ➞ 14796
#
# profit({
#  "cost_price": 225.89,
#  "sell_price": 550.00,
#  "inventory": 100
# }) ➞ 32411
#
# profit({
#  "cost_price": 2.77,
#  "sell_price": 7.95,
#  "inventory": 8500
# }) ➞ 44030

In [ ]:
# 5. Creati o functie care primeste doua numere ca argumente (num, length) si intoarce
# o lista multiplilor lui num pana cand lista ajunge la length elemente. num va fi si el in lista intoarsa.
# De exemplu:
#
# list_of_multiples(7, 5) ➞ [7, 14, 21, 28, 35]
# list_of_multiples(12, 10) ➞ [12, 24, 36, 48, 60, 72, 84, 96, 108, 120]
# list_of_multiples(17, 6) ➞ [17, 34, 51, 68, 85, 102]

In [19]:
[x for x in range(10) if x % 2 == 0]

[0, 2, 4, 6, 8]

In [5]:
# 6. Creati doua functii, una care primeste un string ca argument si intoarce codul Morse echivalent,
# o a doua care primeste stringul encodat si il decodeaza ca text.
# De exemplu:

# encode_morse("HELP ME !") ➞ ".... . .-.. .--.   -- .   -.-.--"
# decode_morse(".... . .-.. .--.   -- .   -.-.--") ➞ "HELP ME !"

# Folositi urmatorul dictionar:

char_to_dots = {
  'A': '.-', 'B': '-...', 'C': '-.-.', 'D': '-..', 'E': '.', 'F': '..-.',
  'G': '--.', 'H': '....', 'I': '..', 'J': '.---', 'K': '-.-', 'L': '.-..',
  'M': '--', 'N': '-.', 'O': '---', 'P': '.--.', 'Q': '--.-', 'R': '.-.',
  'S': '...', 'T': '-', 'U': '..-', 'V': '...-', 'W': '.--', 'X': '-..-',
  'Y': '-.--', 'Z': '--..', ' ': ' ', '0': '-----',
  '1': '.----', '2': '..---', '3': '...--', '4': '....-', '5': '.....',
  '6': '-....', '7': '--...', '8': '---..', '9': '----.',
  '&': '.-...', "'": '.----.', '@': '.--.-.', ')': '-.--.-', '(': '-.--.',
  ':': '---...', ',': '--..--', '=': '-...-', '!': '-.-.--', '.': '.-.-.-',
  '-': '-....-', '+': '.-.-.', '"': '.-..-.', '?': '..--..', '/': '-..-.'
}

# Verificati corectitudinea codarii prin decodare si obtinerea aceluiasi sir. Detectati si secvente invalide.

In [76]:
".... . .-.. .--.   -- .   -.-.--".split()
ord('0'), ord('9')

(48, 57)

In [6]:
# 7. Scrieti o functie care intoarce True daca doua array-uri, combinate, formeaza o secventa consecutiva.
# O secventa consecutiva este o secventa fara gap-uri intre intregi, de exemplu 1, 2, 3, 4, 5 este
# o secventa consecutiva iar 1, 2, 4, 5 nu. Secventele vor fi liste cu intregi unici, care pot fi plasati
# in orice ordine.

# De exemplu:
# consecutive_combo([7, 4, 5, 1], [2, 3, 6 ]) ➞ True
# consecutive_combo([1, 4, 6, 5], [2, 7, 8, 9]) ➞ False
# consecutive_combo([1, 4, 5, 6], [2, 3, 7, 8, 10]) ➞ False
# consecutive_combo([44, 46], [45]) ➞ True

# Dati o metoda de generare a unor astfel de doua secvente consecutive, cu un numar aleator de componente,
# iar cele doua secvente sa fie ordonate aleator.

In [32]:
l1, l2 = [7, 4, 5, 1], [2, 3, 6]
print(l1, l2)

l = sorted(l1 + l2)
sum([abs(x[0] - x[1]) for x in zip(l[1:], l[:-1])]) == len(l) - 1

[7, 4, 5, 1] [2, 3, 6]


True

In [37]:
np.random.randint(2, size=100)

array([1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0])

In [7]:
# 8. Scrieti o functie care aduna doua numere. Numerele vor fi insa siruri (string-uri). De exemplu:
#
# add_str_nums("4", "5") ➞ "9"
# add_str_nums("abcdefg", "3") ➞ "-1"
# add_str_nums("1", "") ➞ "1"
# add_str_nums("1874682736267235927359283579235789257", "32652983572985729") ➞ "1874682736267235927391936562808774986"

# Nu veti folosi functia Python care aduna numere cu orice dimensiune, ci doar va veti verifica cu ajutorul ei.
# Daca un numar are multe zerouri la inceputul sau, acestea vor fi ignorate (trimmed).

In [2]:
l1, l2 = '99945', '347'

[x[0] + x[1] for x in zip([int(x) for x in l1], [0] * 2 + [int(x) for x in l2])]
int(l1) + int(l2)
int('9')

9

In [9]:
# 9. Inmultirea matricilor.
# Conditia este ca numarul de coloane din prima matrice sa fie egal cu numarul de linii din cea de-a doua.
# Ca rezultat al inmultirii veti genera o noua matrice care are acelasi numar de linii ca si prima matrice
# si acelasi numar de coloane ca cea de-a doua.
#
# De exemplu daca inmultiti o matrice n x k cu una k x m , veti obtine una de dimensiuni n x m.
#   
# Creati o functie care primeste doua liste bidimensionale, m1 si m2 ca argumente, si intoarce o matrice sub
# forma de lista bidimensionala.
#
# Daca numarul de coloane din prima matrice nu este egal cu numarul de linii din cea de-a doua se va intoarce
# "eroare".
# De exemplu:

# multiply_matrix([
#  [1, 2, 3],
#  [4, 5, 6],
#  [7, 8, 9]
#], [
#  [1, 2, 3],
#  [4, 5, 6],
#  [7, 8, 9]
#]) ➞ [
#  [30, 36, 42],
#  [66, 81, 96],
#  [102, 126, 150]
#]
#
# Veti verifica rezultatul obtinut folosind numpy. Mai departe veti genera aleator astfel de matrici pe care 
# le veti verifica cu numpy.

In [46]:
a = np.random.randn(3, 3)

In [50]:
assert np.all(a @ np.eye(3) == a)

In [52]:
a = np.array([[1, 2], [3, 4], [-1, -2]])
print(a)
print(f'a.shape: {a.shape}')

[[ 1  2]
 [ 3  4]
 [-1 -2]]
a.shape: (3, 2)


In [56]:
a.transpose()

array([[ 1,  3, -1],
       [ 2,  4, -2]])

In [58]:
a @ a.transpose()

array([[  5,  11,  -5],
       [ 11,  25, -11],
       [ -5, -11,   5]])

In [59]:
np.matmul(a, a.transpose())

array([[  5,  11,  -5],
       [ 11,  25, -11],
       [ -5, -11,   5]])

In [61]:
n, k, m = np.random.randint(low=1, high=20, size=3)

In [62]:
n, k, m

(7, 5, 14)

In [67]:
(np.random.randn(n, k) @ np.random.randn(k, m)).shape

(7, 14)